### PR TITLE
Keep sidebar open on link click

### PR DESCRIPTION
**Pull request by aknobloch3**
- Added JS to reapply the classes needed to keep sidebar open when a page link is clicked
- Also added cursor hover on sidebar headers

http://10.37.0.30:8888/

### CODE REVIEW

**Comment by aknobloch3** [comment]
When you click on intro, the sidebar header is collapsing. Only link that seems to do that.

**Comment by jrauh** [comment]
@aknobloch3 did this get merged to master? I don't see it working.

**Comment by aknobloch3** [comment]
@jrauh I must of missed that part... I was going back and forth on tagging it and must of just decided to do nothing.

**Comment by aknobloch3** [comment]
Just merged to `master`

**Pull request merged**
